### ISSUE TITLE
latest version in git wants deprecated NetCDF-Fotran build (with f90)

### ISSUE THREAD

**Issue by caldodge** [schism-dev/schism#130]
I did a git clone of schishm, and tried to build pschism.

It broke because it didn't find definitions for functions like nf90_put_var.

From checking NetCDF docs, such functions were part of NetCDF-Fortran when it was built with F90, but that hasn't been the default for many years.

Do I need to clone a specific release to eliminate this issue?  Is there a flag I need to set in the makefile? Or do I have to rebuild NetCDF-Fortran with specific flags to create functions with nf90 names?

**Comment by jreniel** [comment]
Which compiler are u using?

**Comment by josephzhang8** [comment]
netcdf libs newer than v4.4 should work fine.

**Comment by caldodge** [comment]
Source is v4.4.4.  Was using Intel mpiifort.  Can't login now, but I think the version was 2021.x.

**Comment by jreniel** [comment]
> Source is v4.4.4. Was using Intel mpiifort. Can't login now, but I think the version was 2021.x.

Reason I ask is because I've seen a similar thing happen when there is a compiler mismatch between the netcdf libs that make is picking up vs the compiler that you are using. Would it be possible for you to give us more context, for example by showing the output of module list as well as the exact command you are passing to CMake?

If it's what I suspect it is, I may have a "magic" command should get things in order but I'll have to follow up cause I don't have access to my server at this very instant so I can give it you.

**Comment by platipodium** [comment]
I've seen this as well when there was a compiler mismatch.

**Comment by caldodge** [comment]
It appears the solution was to build the entire chain with the same
compiler. That's OpenMPI, HDF5, Netcdf-c, and Netcdf-fortran.  Thanks for
everyone's help.
