### ISSUE TITLE
version string for v5.9.0 tag

### ISSUE THREAD

**Issue by hot007** [schism-dev/schism#40]
Hi SCHISM devs,

Just noting that the version string isn't included in the 5.9.0 tag release, so it's still by default building with the string `pschism_5.8.0` rather than `5.9.0`.

cheers
Claire

**Comment by josephzhang8** [comment]
Thank you Claire. I'll let Eli's group handle this, as I hardly use this feature.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

From: Claire Trenham ***@***.***
Sent: Sunday, August 15, 2021 10:30 PM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] version string for v5.9.0 tag (#40)


[EXTERNAL to VIMS received message]


Hi SCHISM devs,

Just noting that the version string isn't included in the 5.9.0 tag release, so it's still by default building with the string pschism_5.8.0 rather than 5.9.0.

cheers
Claire

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fissues%2F40&data=04%7C01%7Cyjzhang%40vims.edu%7Cb96fccf842fa4a22e6fb08d9605dbdae%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637646778008094223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xnYRTx3O5kzIDvF8n1heC14TgLo0zeYCu%2FL%2FjYf%2FEgE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBKNZ35OTTZFLWZB7GZXUTT5BZ2LANCNFSM5CG2NM6A&data=04%7C01%7Cyjzhang%40vims.edu%7Cb96fccf842fa4a22e6fb08d9605dbdae%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637646778008094223%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xKkHEwMnIIQFSVlYTpBFZx1yWha%2BddkHYTAvn6TnlZE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyjzhang%40vims.edu%7Cb96fccf842fa4a22e6fb08d9605dbdae%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637646778008104178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mjLdHCNMfmjJvOhekY2FL9gTvx70J%2BQL8PDhYfqvEKk%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cyjzhang%40vims.edu%7Cb96fccf842fa4a22e6fb08d9605dbdae%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637646778008104178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MR2CvHp89tUi24Y2AkBbUUwP0jpd5GksprvUeKY7m1o%3D&reserved=0>.

**Comment by hot007** [comment]
Set in the `EXEC` field of `Make.defs.local`, how to change automatically if needed? Closing this issue in favour of #84.
