### ISSUE TITLE
schism --version

### ISSUE THREAD

**Issue by brey** [schism-dev/schism#50]
Due to changes in the output of headers to the `local_to_global_0000*` files between `v5.8` & `v5.9`, in order to support both versions in `pyPoseidon` I need a way to easily determine the installed version of schism. 

Is there a way to have the output of 

`schism --version`

returning the version?

**Comment by josephzhang8** [comment]
Hi George:

Yes you can query the version this way:

./pschism_JAMES_TVD-VL -v
schism v5.9.0
git hash 657157a

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

From: George Breyiannis ***@***.***>
Sent: Thursday, November 11, 2021 10:49 AM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] schism --version (Issue #50)


[EXTERNAL to VIMS received message]


Due to changes in the output of headers to the local_to_global_0000* files between v5.8 & v5.9, in order to support both versions in pyPoseidon I need a way to easily determine the installed version of schism.

Is there a way to have the output of

schism --version

returning the version?

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fissues%2F50&data=04%7C01%7Cyjzhang%40vims.edu%7C96a0c15478d349e5076408d9a52ac1ac%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637722425338758698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DsFlb%2BykIsuZIq2Pv7JBHENEFpbWmAPQtLFv4wDoYSU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBKNZZRJJNSI6J2BSWGF6DULPQWDANCNFSM5H2YTAXQ&data=04%7C01%7Cyjzhang%40vims.edu%7C96a0c15478d349e5076408d9a52ac1ac%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637722425338768655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1fyChXBiVZ1A8z0nhJ3icUfQf308D4TBTsKkG2NPykw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cyjzhang%40vims.edu%7C96a0c15478d349e5076408d9a52ac1ac%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637722425338768655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A9aIsTUItgbyRVi4knOapGs3tqDrsJtHbBEppdyFpN8%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cyjzhang%40vims.edu%7C96a0c15478d349e5076408d9a52ac1ac%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637722425338778611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N9WRZ%2BUHkFlkzDw9u0VX6SII%2FKS7MngeuZ4moCGLtVY%3D&reserved=0>.

**Comment by brey** [comment]
Thanks Joseph. If one clones the repo and builds locally this works. 

However, if one builds from the `zip/tar` release files there is no local `.git` folder and the return is 

```
❯ ./bin/pschism_TVD-VL -v
 
 schism develop
 git hash none

```

BTW, conda is using also the `.gz` files from the tag releases.

**Comment by josephzhang8** [comment]
I’ll let Eli comment on this. I think the query function depends on git clone, as you stated. I’ve never tried offline download/compile.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by josephzhang8** [comment]
This is certainly an under-rehearsed part of the build. If you can fake it until next week I'll take a look at it then.
________________________________
From: Y. Joseph Zhang ***@***.***>
Sent: Thursday, November 11, 2021 2:42 PM
To: schism-dev/schism ***@***.***>; schism-dev/schism ***@***.***>
Cc: Comment ***@***.***>; Ateljevich, ***@***.*** ***@***.***>
Subject: RE: [schism-dev/schism] schism --version (Issue #50)


I’ll let Eli comment on this. I think the query function depends on git clone, as you stated. I’ve never tried offline download/compile.



-Joseph



Y. Joseph Zhang

Web: schism.wiki

Office: 804 684 7466

**Comment by brey** [comment]
No worries. We have a workaround for now. This is more of a feature request.

**Comment by josephzhang8** [comment]
Issue closed per @brey
