### ISSUE TITLE
:coffin: dead/deprecated/backup codes in the main branch

### ISSUE THREAD

**Issue by jamal919** [schism-dev/schism#83]
Following up on issue #58, it seems to me that `src/WWMIII.Sept2020` has reached its time for deprecation (2-years). Two tag release has been created since the creation of this backup, and the current `WWMIII` also received some bug fixes and new features e.g., https://github.com/schism-dev/schism/commit/40baa99e2299c440381045d3692784a0e8cdaaf3, https://github.com/schism-dev/schism/commit/6524e19c5d5edca7d5c60eb4234c7d44bfdbe015, https://github.com/schism-dev/schism/commit/3906b0cec4859b51910add7f1a39a21df7dc160e, https://github.com/schism-dev/schism/commit/567b61235fa9a815ac7b4fa19984fca42fa9f381, https://github.com/schism-dev/schism/commit/73f7e1b36f16987fab0373baac012074db41f25c, https://github.com/schism-dev/schism/commit/ff5ad7546c5cec721e83f4ec55484d43e5a160bb, https://github.com/schism-dev/schism/commit/9b711aff8ee2c382e24e175a3b5b2e9a0b4761b5. 

IMO, as everything is already tracked by git, we would be able to checkout to this exact version in the foreseeable future with `git checkout <sha>` command after removal. As such, backup folders of codes seems to be only contributing to make the folder structure unnecessarily convoluted. 

Thanks.

**Comment by josephzhang8** [comment]
Removed.

**Comment by josephzhang8** [comment]
I agree. I'll remove that dir if Aron and Xavier are good with that. Thx Jamal for the reminder.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

From: Jamal Uddin Khan ***@***.***>
Sent: Saturday, September 10, 2022 7:17 AM
To: schism-dev/schism ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [schism-dev/schism] :coffin: dead/deprecated/backup codes in the main branch (Issue #83)


[EXTERNAL to VIMS received message]


Following up on issue #58<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fissues%2F58&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006727510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F5djQohZ4vQWqJ%2FPA0hDbGEqg459qLDq32XCv4B8T2c%3D&reserved=0>, it seems to me that src/WWMIII.Sept2020 has reached its time for deprecation (2-years). Two tag release has been created since the creation of this backup, and the current WWMIII also received some bug fixes and new features e.g., 40baa99<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F40baa99e2299c440381045d3692784a0e8cdaaf3&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006727510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BJUUSaxj3go%2BnfOOs8AeITRAldQwlyQTRZaQ7EyogEQ%3D&reserved=0>, 6524e19<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F6524e19c5d5edca7d5c60eb4234c7d44bfdbe015&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006727510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ntqyv74S%2BoOvyKvAWpFZA1u3Szm5B%2BtaJHIwGuSJCPw%3D&reserved=0>, 3906b0c<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F3906b0cec4859b51910add7f1a39a21df7dc160e&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006883727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E5Jd6ksCjoD29A0UTsGRAzNvuQe9OmYAZzXdsZKMpzY%3D&reserved=0>, 567b612<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F567b61235fa9a815ac7b4fa19984fca42fa9f381&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006883727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v4jsawrKRFWfxpD9hN5DIMi8h7p7HMSOJE8baWW%2Fjeg%3D&reserved=0>, 73f7e1b<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F73f7e1b36f16987fab0373baac012074db41f25c&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006883727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y1XpbsEqYw9iFe9aYC2YxGVs2QhNDoeIgGrIuninNQE%3D&reserved=0>, ff5ad75<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2Fff5ad7546c5cec721e83f4ec55484d43e5a160bb&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006883727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iOnSeCkKtgHdayfDONndHBILzmJBFe9lCN9FBlPYX%2Bk%3D&reserved=0>, 9b711af<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fschism-dev%2Fschism%2Fcommit%2F9b711aff8ee2c382e24e175a3b5b2e9a0b4761b5&data=05%7C01%7Cyjzhang%40vims.edu%7Cad82d520f4644aa264be08da931ded02%7C8cbcddd9588d4e3b9c1e2367dbdf1740%7C0%7C0%7C637984054006883727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oLPa4eOfwgFhdlCxam4J3lLbfG8rDvRXGeCERxW9hHg%3D&reserved=0>.

IMO, as everything is already tracked by git, we would be able to checkout to this exact version in the foreseeable future with git checkout <sha> command after removal. As such, backup folders of codes seems to be only contributing to make the folder structure unnecessarily convoluted.

Thanks.

-

**Comment by jamal919** [comment]
Hello Joseph, 

I am guessing the the messages are coming (or being delivered) later. You actually took care of the folder about 1 month ago. 

Thanks.

**Comment by jamal919** [comment]
I see! I suspected so. FYI, I also have schism-dev/schism followed, but did not receive the messages. It seems it is isolated to you perhaps. 

With best of luck.
